"""initial schema

Revision ID: 5ae8d8c5e365
Revises: 
Create Date: 2026-09-12 22:23:09.837853
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('input_hash')
    )
    op.create_table('ai_cost_ledger',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('batch_hash', sa.String(length=64), nullable=False),
    sa.Column('estimated_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('actual_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_cursor',
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.Column('last_source_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stir', sa.String(length=32), nullable=True),
    sa.Column('name_canonical', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stir')
    )
    op.create_table('raw_snapshot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_snapshot_sha256'), 'raw_snapshot', ['sha256'], unique=False)
    op.create_table('organization_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name_raw', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name_raw', name='uq_org_alias')
    )
    op.create_index('ix_organization_alias_name_trgm', 'organization_alias', ['name_raw'], unique=False, postgresql_using='gin', postgresql_ops={'name_raw': 'gin_trgm_ops'})
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('procedure_type', sa.Text(), nullable=True),
    sa.Column('customer_org_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('start_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('raw_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['raw_snapshot_id'], ['raw_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_procedure_source_id')
    )
    op.create_index(op.f('ix_procedure_completed_at'), 'procedure', ['completed_at'], unique=False)
    op.create_table('award',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('supplier_org_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('procedure_id')
    )
    op.create_table('classification',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('is_it', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('model_hint', sa.Text(), nullable=True),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('procedure_id')
    )
    op.create_index(op.f('ix_classification_category'), 'classification', ['category'], unique=False)
    op.create_table('lot_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=3), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('unit_price_raw', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_item_procedure_id'), 'lot_item', ['procedure_id'], unique=False)
    op.create_table('renewal_opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_org_id', sa.Integer(), nullable=True),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('last_purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifecycle_months', sa.Integer(), nullable=False),
    sa.Column('expected_renewal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_by_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procedure_id', name='uq_renewal_procedure')
    )
    op.create_index(op.f('ix_renewal_opportunity_contact_by_at'), 'renewal_opportunity', ['contact_by_at'], unique=False)
    op.create_index(op.f('ix_renewal_opportunity_customer_org_id'), 'renewal_opportunity', ['customer_org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renewal_opportunity_customer_org_id'), table_name='renewal_opportunity')
    op.drop_index(op.f('ix_renewal_opportunity_contact_by_at'), table_name='renewal_opportunity')
    op.drop_table('renewal_opportunity')
    op.drop_index(op.f('ix_lot_item_procedure_id'), table_name='lot_item')
    op.drop_table('lot_item')
    op.drop_index(op.f('ix_classification_category'), table_name='classification')
    op.drop_table('classification')
    op.drop_table('award')
    op.drop_index(op.f('ix_procedure_completed_at'), table_name='procedure')
    op.drop_table('procedure')
    op.drop_index('ix_organization_alias_name_trgm', table_name='organization_alias', postgresql_using='gin', postgresql_ops={'name_raw': 'gin_trgm_ops'})
    op.drop_table('organization_alias')
    op.drop_index(op.f('ix_raw_snapshot_sha256'), table_name='raw_snapshot')
    op.drop_table('raw_snapshot')
    op.drop_table('organization')
    op.drop_table('import_cursor')
    op.drop_table('ai_cost_ledger')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
